Repository yays-or-nays/yays-or-nays-BE, pull requests merged in 2021-04, with the labels that each got.

#7 Db setup
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/assets/config/manifest.js
  app/controllers/graphql_controller.rb
  app/graphql/mutations/.keep
  app/graphql/mutations/base_mutation.rb
  app/graphql/types/.keep
  app/graphql/types/base_argument.rb
  app/graphql/types/base_enum.rb
  app/graphql/types/base_field.rb
  app/graphql/types/base_input_object.rb
  app/graphql/types/base_interface.rb
  app/graphql/types/base_object.rb
  app/graphql/types/base_scalar.rb
  app/graphql/types/base_union.rb
  app/graphql/types/hot_take_type.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  app/graphql/types/tag_type.rb
  app/graphql/yays_or_nays_be_schema.rb
  app/models/hot_take.rb
  app/models/tag.rb
  config/application.rb
  config/routes.rb
  db/migrate/20210409002107_create_hot_takes.rb
  db/migrate/20210409143000_create_tags.rb
  db/migrate/20210409222339_create_tagged_takes.rb
  db/migrate/20210409224601_drop_tagged_takes_table.rb
  db/migrate/20210409225130_add_references_to_hot_takes.rb
  db/schema.rb
  pull_request_template.md
  spec/models/hot_take_spec.rb
  spec/models/tag_spec.rb
  spec/rails_helper.rb
Labels: BE, GraphQL, Phase 1

#8 CircleCI configuration setup
  .circleci/config.yml
Labels: BE, Chore, enhancement

#9 Graphql queries sy
  .ruby-version
  Gemfile
  Gemfile.lock
  app/graphql/mutations/base_mutation.rb
  app/graphql/mutations/increment_no_vote.rb
  app/graphql/mutations/increment_yes_vote.rb
  app/graphql/types/base_object.rb
  app/graphql/types/mutation_type.rb
  app/graphql/types/query_type.rb
  config/initializers/assets.rb
  db/seeds.rb
  public/assets/graphiql/rails/application-31eddba0b591aeaf3c26ec58ff19af49371c0599526cac71dc5d602c2cb1306f.js
  spec/rails_helper.rb
  spec/requests/category_query_spec.rb
Labels: BE, GraphQL, Phase 1

#10 Add API contract section to README
  README.md
Labels: BE, GraphQL, Phase 1, documentation

#11 Add more examples of hot_takes
  db/seeds.rb
Labels: BE, Chore, Phase 1

#12 Add image URLs to seeds file
  db/seeds.rb
Labels: BE, Chore, Phase 1

#13 🌱 Update HotTake seedfile
  db/seeds.rb
Labels: BE, Chore, Phase 1

#14 Graphql req testing
  spec/requests/category_query_spec.rb
  spec/requests/queries/category_query_spec.rb
  spec/requests/queries/hot_take_by_category_request_spec.rb
Labels: BE, GraphQL, Phase 1, Testing

#15 Update seed images
  db/seeds.rb
Labels: BE

#16 Saundra seeds2
  db/seeds.rb
Labels: BE, Chore, Phase 1

#17 Graphql req testing
  .gitignore
  app/graphql/types/query_type.rb
  spec/rails_helper.rb
  spec/requests/mutations/increment_no_vote_by_one_spec.rb
  spec/requests/mutations/increment_yes_vote_by_one_spec.rb
Labels: BE, GraphQL, Phase 1, Testing

#18 📝 Add installation steps to README
  README.md
Labels: BE, Phase 1, documentation
